/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Database.Connect;
import Process.Ban;
import UI.BanHang.pnlChiTietBan;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author ThanhNam
 */
public class frmBanHang extends javax.swing.JInternalFrame {
//    Connect conn = new Connect();
    private Connection cn = Connect.ketnoi("DoAn_QLCafe");
    public ArrayList<Ban> GetBan(int maban){
        ArrayList<Ban> arrBan = null;
        String sql;
        if(maban == 0)
            sql = "Select * From ban";
        else
            sql = "Select * From ban Where MaBan = '"+maban+"'";
        try{
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            arrBan = new ArrayList<Ban>();
            while(rs.next()){
                Ban sp = new Ban(rs.getInt(1), rs.getString(2), rs.getString(3));
                arrBan.add(sp);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi !");
        }
        return arrBan; 
    }
    /**
     * Creates new form NewJInternalFrame
     */
    pnlChiTietBan panel;
    ArrayList<Ban> arrBan;
    ArrayList<Ban> ban;
    int MaBan;
    
    public static frmBanHang bh;
    
    public frmBanHang() {
        initComponents();
        bh = this;
        FillBan();
    }
    

    
    public void FillBan(){
        arrBan = GetBan(0);
        if(arrBan != null){
            pnlBan.removeAll();
            JButton[] btn = new JButton[arrBan.size()];
            for(int i=0;i<arrBan.size();i++){
                btn[i] = new JButton();
                btn[i].setName(String.valueOf(arrBan.get(i).getMaban()));
                String mb = arrBan.get(i).getTenban();
                btn[i].setText(mb);
//                btn[i].setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Images/ico-Table.png")));
                Border thickBorder = new LineBorder(Color.WHITE,8);
                btn[i].setBorder(thickBorder);
                btn[i].setBackground(Color.decode("#8080ff"));
                btn[i].setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
                btn[i].setForeground(new java.awt.Color(51, 51, 51));
                if(arrBan.get(i).getTrangthai().equals("Trống")){
                    btn[i].setBackground(Color.decode("#66ff66"));
                }
                if(arrBan.get(i).getTrangthai().equals("Đang Có Khách")){
                    btn[i].setBackground(Color.decode("#ff6699"));
                }                
                btn[i].setPreferredSize(new Dimension(90, 70));

                btn[i].addMouseListener(new MouseAdapter() {
                        @Override
                        public void mousePressed(MouseEvent e) {
                            ban = GetBan(Integer.parseInt(e.getComponent().getName()));
                            if(ban != null){                            
                                panel = new pnlChiTietBan(ban.get(0).getMaban(), ban.get(0).getTenban(), ban.get(0).getTrangthai());
                                pnlMain.removeAll();
                                pnlMain.add(panel);
                                pnlMain.updateUI();
                            }
                        }                    
                });
                pnlBan.add(btn[i]);
                pnlBan.updateUI();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBan = new javax.swing.JPanel();
        pnlMain = new javax.swing.JPanel();

        pnlBan.setBackground(new java.awt.Color(204, 204, 255));
        pnlBan.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnlMain.setBackground(new java.awt.Color(204, 255, 255));
        pnlMain.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMain.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBan, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBan, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel pnlBan;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
