/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import UI.QuanLy.frmQLNhanVien;
import UI.QuanLy.frmQLBan;
import UI.QuanLy.frmQLSanPham;
import UI.QuanLy.frmQLlsp;

/**
 *
 * @author ThanhNam
 */
public class frmQuanLy extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmQuanLy
     */
    
    frmQLNhanVien nhanVien;
    frmQLBan ban;
    frmQLlsp loaisp;
    frmQLSanPham sanPham;
    
    public frmQuanLy() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSanPham = new javax.swing.JButton();
        btnLSP = new javax.swing.JButton();
        btnBan = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        Desktop = new javax.swing.JDesktopPane();

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnSanPham.setBackground(new java.awt.Color(102, 255, 255));
        btnSanPham.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSanPham.setText("Quản Lý Sản Phẩm");
        btnSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanPhamActionPerformed(evt);
            }
        });

        btnLSP.setBackground(new java.awt.Color(102, 255, 255));
        btnLSP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLSP.setText("Quản Lý Loại Sản Phẩm");
        btnLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLSPActionPerformed(evt);
            }
        });

        btnBan.setBackground(new java.awt.Color(102, 255, 255));
        btnBan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBan.setText("Quản Lý Bàn");
        btnBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanActionPerformed(evt);
            }
        });

        btnNhanVien.setBackground(new java.awt.Color(102, 255, 255));
        btnNhanVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnNhanVien.setText("Quản Lý Nhân Viên");
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLSP, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(btnBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 392, Short.MAX_VALUE))
        );

        Desktop.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 863, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanPhamActionPerformed
        // TODO add your handling code here:
        Desktop.removeAll();
        sanPham = new frmQLSanPham();
        sanPham.setVisible(true);
        Desktop.add(sanPham);
        Desktop.updateUI();
    }//GEN-LAST:event_btnSanPhamActionPerformed

    private void btnLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLSPActionPerformed
        // TODO add your handling code here:
        Desktop.removeAll();
        loaisp = new frmQLlsp();
        loaisp.setVisible(true);
        Desktop.add(loaisp);
        Desktop.updateUI();
    }//GEN-LAST:event_btnLSPActionPerformed

    private void btnBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanActionPerformed
        // TODO add your handling code here:
        Desktop.removeAll();
        ban = new frmQLBan();
        ban.setVisible(true);
        Desktop.add(ban);
        Desktop.updateUI();
    }//GEN-LAST:event_btnBanActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
        Desktop.removeAll();
        nhanVien = new frmQLNhanVien();
        nhanVien.setVisible(true);
        Desktop.add(nhanVien);
        Desktop.updateUI();
    }//GEN-LAST:event_btnNhanVienActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JButton btnBan;
    private javax.swing.JButton btnLSP;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
